(() => {
  "use strict";
  const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
  const categories = [
    { id: "All", label: "All", icon: "✦" }, { id: "Pizza", label: "Pizza", icon: "🍕" },
    { id: "Burgers", label: "Burgers", icon: "🍔" }, { id: "Indian", label: "Indian", icon: "🍛" },
    { id: "Healthy", label: "Healthy", icon: "🥗" }, { id: "Desserts", label: "Desserts", icon: "🍰" }, { id: "Asian", label: "Asian", icon: "🍜" }
  ];
  const restaurants = [
    { id: "saffron-yard", name: "Saffron Yard", cuisine: "North Indian · Biryani · Kebabs", categories: ["Indian"], rating: "4.8", eta: "25–30 min", fee: "Free delivery", tag: "FOODIE FAVOURITE", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=86", location: { lat: 18.535, lng: 73.842 } },
    { id: "crust-and-craft", name: "Crust & Craft", cuisine: "Wood-fired pizza · Italian", categories: ["Pizza"], rating: "4.7", eta: "20–25 min", fee: "Free delivery", tag: "BESTSELLER", image: "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=86", location: { lat: 18.519, lng: 73.865 } },
    { id: "green-room", name: "The Green Room", cuisine: "Fresh bowls · Salads · Smoothies", categories: ["Healthy"], rating: "4.9", eta: "15–20 min", fee: "₹20 delivery", tag: "LIGHT & LOVELY", image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=86", location: { lat: 18.506, lng: 73.858 } },
    { id: "bao-house", name: "Bao House", cuisine: "Asian street food · Dumplings", categories: ["Asian"], rating: "4.6", eta: "30–35 min", fee: "Free delivery", tag: "NEW ON FOODIE", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=900&q=86", location: { lat: 18.526, lng: 73.876 } },
    { id: "bun-and-bloom", name: "Bun & Bloom", cuisine: "Smash burgers · Fries · Shakes", categories: ["Burgers"], rating: "4.7", eta: "20–25 min", fee: "₹10 delivery", tag: "MUST TRY", image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=86", location: { lat: 18.513, lng: 73.828 } },
    { id: "sugar-story", name: "Sugar Story", cuisine: "Desserts · Cakes · Ice cream", categories: ["Desserts"], rating: "4.8", eta: "25–30 min", fee: "Free delivery", tag: "SWEET SPOT", image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=86", location: { lat: 18.548, lng: 73.868 } }
  ];
  const menus = {
    "saffron-yard": [
      { id: "butter-chicken-bowl", name: "Smoky butter chicken bowl", description: "Creamy makhani, charred chicken and fragrant jeera rice.", price: 249, emoji: "🍗", veg: false }, { id: "paneer-tikka", name: "Lahori paneer tikka", description: "Tandoor-fired paneer, peppers and mint chutney.", price: 219, emoji: "🧀", veg: true }, { id: "saffron-biryani", name: "Saffron dum biryani", description: "Long-grain rice, whole spices and crisp fried onions.", price: 279, emoji: "🍛", veg: false }, { id: "garlic-naan", name: "Butter garlic naan", description: "Soft tandoor naan finished with garlic and coriander.", price: 69, emoji: "🫓", veg: true }
    ],
    "crust-and-craft": [
      { id: "truffle-funghi", name: "Truffle funghi", description: "Wild mushrooms, mozzarella, garlic cream and herbs.", price: 329, emoji: "🍕", veg: true }, { id: "spicy-pepperoni", name: "Spicy pepperoni", description: "Cupped pepperoni, smoked mozzarella and chilli honey.", price: 369, emoji: "🍕", veg: false }, { id: "burrata-tomato", name: "Burrata & tomato", description: "Creamy burrata, basil oil, tomato and sourdough.", price: 289, emoji: "🍅", veg: true }, { id: "tiramisu", name: "House tiramisu", description: "Espresso-soaked sponge, mascarpone and cocoa.", price: 179, emoji: "🍰", veg: true }
    ],
    "green-room": [
      { id: "rainbow-bowl", name: "Rainbow nourish bowl", description: "Quinoa, roasted veg, avocado and sesame lime dressing.", price: 269, emoji: "🥗", veg: true }, { id: "crispy-tofu", name: "Crispy tofu salad", description: "Five-spice tofu, greens, herbs and peanut dressing.", price: 239, emoji: "🥬", veg: true }, { id: "avocado-toast", name: "Avocado toast", description: "Sourdough, smashed avocado, chilli flakes and seeds.", price: 199, emoji: "🥑", veg: true }, { id: "mango-smoothie", name: "Mango sunshine", description: "Alphonso mango, yoghurt and a little cardamom.", price: 149, emoji: "🥭", veg: true }
    ],
    "bao-house": [
      { id: "crispy-chicken-bao", name: "Crispy chicken bao", description: "Steamed bao, crunchy chicken, slaw and chilli mayo.", price: 229, emoji: "🥟", veg: false }, { id: "edamame-dumplings", name: "Edamame dumplings", description: "Silky wrappers, edamame, ginger and sesame.", price: 189, emoji: "🥟", veg: true }, { id: "ramen-bowl", name: "Miso ramen bowl", description: "Miso broth, noodles, corn, greens and a soft egg.", price: 279, emoji: "🍜", veg: true }, { id: "sesame-cucumber", name: "Sesame cucumber crunch", description: "Chilled cucumber, garlic, chilli oil and sesame.", price: 119, emoji: "🥒", veg: true }
    ],
    "bun-and-bloom": [
      { id: "bloom-smash", name: "Bloom smash burger", description: "Two smashed patties, American cheese, pickles and house sauce.", price: 289, emoji: "🍔", veg: false }, { id: "crispy-chicken-burger", name: "Crispy chicken burger", description: "Buttermilk chicken, lettuce, slaw and hot honey.", price: 259, emoji: "🍔", veg: false }, { id: "loaded-fries", name: "Loaded chilli fries", description: "Golden fries, cheese sauce, jalapeños and spring onion.", price: 169, emoji: "🍟", veg: true }, { id: "salted-caramel-shake", name: "Salted caramel shake", description: "Vanilla soft serve, caramel and sea salt.", price: 159, emoji: "🥤", veg: true }
    ],
    "sugar-story": [
      { id: "raspberry-cloud", name: "Raspberry cloud cake", description: "Vanilla sponge, raspberry compote and whipped cream.", price: 199, emoji: "🍰", veg: true }, { id: "chocolate-tart", name: "Dark chocolate tart", description: "Bittersweet chocolate ganache, sea salt and cocoa.", price: 189, emoji: "🍫", veg: true }, { id: "pistachio-kulfi", name: "Pistachio kulfi", description: "Slow-set kulfi, roasted pistachio and saffron.", price: 129, emoji: "🍨", veg: true }, { id: "cookie-box", name: "Warm cookie box", description: "Four gooey chocolate chip cookies for the table.", price: 229, emoji: "🍪", veg: true }
    ]
  };
  const mapBounds = { minLat: 18.47, maxLat: 18.59, minLng: 73.77, maxLng: 73.93 };
  const deliveryLocation = { lat: 18.5074, lng: 73.8077 };
  const safeParse = (value, fallback) => { try { return value ? JSON.parse(value) : fallback; } catch { return fallback; } };
  const persisted = safeParse(localStorage.getItem("foodie-state"), {});
  const state = { view: "home", activeCategory: "All", search: "", cart: persisted.cart || {}, orders: Array.isArray(persisted.orders) ? persisted.orders : [], activeOrder: persisted.activeOrder || null, selectedRestaurantId: null, modal: null, firebaseConfigured: Boolean(window.FoodieFirebase?.configured), liveLocation: null, liveIsFirebase: false, locationUnsubscribe: null, listeningOrderId: null, riderWatchId: null, riderOrderId: null, riderName: "Foodie Rider", riderSharing: false, demoTimer: null, demoStep: 0 };
  const modalRoot = document.getElementById("modalRoot");
  const toast = document.getElementById("toast");
  let toastTimer = null;
  const firebaseApi = () => window.FoodieFirebase || null;
  const money = (value) => currency.format(Number(value) || 0);
  const escapeHtml = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
  const restaurantById = (id) => restaurants.find((restaurant) => restaurant.id === id) || restaurants[0];
  const menuItemByKey = (key) => { const [restaurantId, itemId] = String(key).split("::"); const item = (menus[restaurantId] || []).find((entry) => entry.id === itemId); return item ? { ...item, restaurantId } : null; };
  const cartEntries = () => Object.entries(state.cart).map(([key, quantity]) => ({ ...menuItemByKey(key), key, quantity: Number(quantity) || 0 })).filter((entry) => entry.id && entry.quantity > 0);
  const cartCount = () => cartEntries().reduce((total, item) => total + item.quantity, 0);
  const cartSubtotal = () => cartEntries().reduce((total, item) => total + item.price * item.quantity, 0);
  const persist = () => localStorage.setItem("foodie-state", JSON.stringify({ cart: state.cart, orders: state.orders, activeOrder: state.activeOrder }));
  const formatDate = (timestamp) => timestamp ? new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" }).format(new Date(timestamp)) : "Just now";
  function showToast(message) { clearTimeout(toastTimer); toast.textContent = message; toast.classList.add("show"); toastTimer = setTimeout(() => toast.classList.remove("show"), 2800); }
  function setView(view) { state.view = view; document.querySelectorAll(".view").forEach((section) => section.classList.toggle("active", section.id === `${view}View`)); document.querySelectorAll(".nav-item").forEach((item) => item.classList.toggle("active", item.dataset.view === view)); if (view === "track" && state.activeOrder) subscribeToRider(state.activeOrder.id); window.scrollTo({ top: 0, behavior: "smooth" }); renderView(view); }
  function renderView(view) { if (view === "home") { renderCategories(); renderRestaurants(); } if (view === "orders") renderOrders(); if (view === "track") renderTrack(); if (view === "profile") renderProfile(); renderCartPeek(); }
  function renderCategories() { const rail = document.getElementById("categoryRail"); if (!rail) return; rail.innerHTML = categories.map((category) => `<button class="category-chip ${state.activeCategory === category.id ? "active" : ""}" data-action="category" data-category="${category.id}" type="button" role="tab" aria-selected="${state.activeCategory === category.id}"><span class="category-icon" aria-hidden="true">${category.icon}</span><span>${category.label}</span></button>`).join(""); }
  function renderRestaurants() {
    const grid = document.getElementById("restaurantGrid"); if (!grid) return;
    const query = state.search.trim().toLowerCase();
    const filtered = restaurants.filter((restaurant) => { const menuText = (menus[restaurant.id] || []).map((item) => `${item.name} ${item.description}`).join(" "); return (state.activeCategory === "All" || restaurant.categories.includes(state.activeCategory)) && (!query || `${restaurant.name} ${restaurant.cuisine} ${menuText}`.toLowerCase().includes(query)); });
    if (!filtered.length) { grid.innerHTML = `<div class="empty-search"><strong>No delicious matches yet.</strong><br /><span>Try another dish, restaurant or category.</span></div>`; return; }
    grid.innerHTML = filtered.map((restaurant) => `<article class="restaurant-card" data-action="open-restaurant" data-restaurant-id="${restaurant.id}" tabindex="0" role="button" aria-label="Open ${escapeHtml(restaurant.name)} menu"><div class="restaurant-image" style="background-image:url('${restaurant.image}')"><span class="restaurant-tag">${escapeHtml(restaurant.tag)}</span><button class="restaurant-fav" data-action="favorite" data-restaurant-id="${restaurant.id}" type="button" aria-label="Save ${escapeHtml(restaurant.name)}">♡</button></div><div class="restaurant-body"><h3>${escapeHtml(restaurant.name)}</h3><p class="restaurant-cuisine">${escapeHtml(restaurant.cuisine)}</p><div class="restaurant-meta"><span class="rating">${restaurant.rating}</span><span class="meta-dot"></span><span>${restaurant.eta}</span><span class="meta-dot"></span><span class="delivery-free">${escapeHtml(restaurant.fee)}</span></div></div></article>`).join("");
  }
  function statusInfo(status) { return ({ confirmed: { label: "Confirmed", className: "waiting", index: 0 }, preparing: { label: "Preparing", className: "waiting", index: 1 }, on_the_way: { label: "On the way", className: "", index: 2 }, delivered: { label: "Delivered", className: "", index: 3 } })[status] || { label: "Confirmed", className: "waiting", index: 0 }; }
  function orderCardMarkup(order, active) { const restaurant = restaurantById(order.restaurantId); const status = statusInfo(order.status); const items = (order.items || []).map((item) => `${item.quantity}× ${escapeHtml(item.name)}`).join(" · "); return `<article class="order-card ${active ? "active-order-card" : ""}"><div class="order-label-row"><small>${active ? "Current order" : escapeHtml(formatDate(order.createdAt))}</small><span class="status-pill ${status.className}">${status.label}</span></div><h3>${escapeHtml(restaurant.name)}</h3><p class="order-items-line">${items || "Your Foodie order"}</p><div class="order-footer"><div><span class="order-total">${money(order.total)}</span><span class="order-date"> · ${escapeHtml(order.id)}</span></div>${active ? `<button class="small-action" data-action="track-order" type="button">Track order →</button>` : `<button class="small-action secondary" data-action="reorder" data-order-id="${order.id}" type="button">Order again</button>`}</div></article>`; }
  function renderOrders() { const target = document.getElementById("orderContent"); if (!target) return; const history = state.orders.filter((order) => order.id !== state.activeOrder?.id); if (!state.activeOrder && !history.length) { target.innerHTML = `<div class="empty-state"><div><div class="empty-state-emoji">🍽️</div><h3>Your next favourite is waiting.</h3><p>Place an order and it will appear here with live delivery updates.</p><button class="primary-button" data-action="browse-menu" type="button">Browse restaurants <span>→</span></button></div></div>`; return; } target.innerHTML = (state.activeOrder ? orderCardMarkup(state.activeOrder, true) : "") + (history.length ? `<div class="profile-section-title">Previous orders</div>${history.map((order) => orderCardMarkup(order, false)).join("")}` : ""); }
  const clamp = (value, min, max) => Math.min(max, Math.max(min, value));
  function mapPosition(location) { const lng = Number(location?.lng ?? deliveryLocation.lng); const lat = Number(location?.lat ?? deliveryLocation.lat); return { left: clamp(((lng - mapBounds.minLng) / (mapBounds.maxLng - mapBounds.minLng)) * 100, 7, 91), top: clamp(100 - ((lat - mapBounds.minLat) / (mapBounds.maxLat - mapBounds.minLat)) * 100, 9, 88) }; }
  function routeLineStyle(from, to) { const a = mapPosition(from); const b = mapPosition(to); const dx = b.left - a.left; const dy = b.top - a.top; return `left:${a.left}%;top:${a.top}%;width:${Math.sqrt(dx * dx + dy * dy)}%;transform:rotate(${Math.atan2(dy, dx) * 180 / Math.PI}deg)`; }
  function renderTrack() {
    const target = document.getElementById("trackContent"); if (!target) return; const order = state.activeOrder;
    if (!order) { target.innerHTML = `<div class="empty-state"><div><div class="empty-state-emoji">🛵</div><h3>No order to track.</h3><p>Once your order is accepted, you can follow your rider right here.</p><button class="primary-button" data-action="browse-menu" type="button">Find something tasty <span>→</span></button></div></div>`; return; }
    const restaurant = restaurantById(order.restaurantId); const status = statusInfo(order.status); const riderLocation = state.liveLocation || restaurant.location; const riderPosition = mapPosition(riderLocation); const restaurantPosition = mapPosition(restaurant.location); const homePosition = mapPosition(deliveryLocation); const live = Boolean(state.liveLocation); const liveText = live ? (state.liveIsFirebase ? "Live location" : "Demo location") : "Waiting for rider"; const eta = order.status === "delivered" ? "Delivered" : order.status === "on_the_way" ? "Arriving in 12–18 min" : "Kitchen is getting started"; const steps = ["Confirmed", "Preparing", "On the way", "Delivered"];
    target.innerHTML = `<article class="tracking-card"><div class="tracking-topline"><div><span class="section-kicker">${escapeHtml(order.id)}</span><h2>${escapeHtml(eta)}</h2></div><span class="live-badge ${live && !state.liveIsFirebase ? "demo" : ""}">${liveText}</span></div><div class="tracking-map" aria-label="Live rider map"><div class="map-road road-one"></div><div class="map-road road-two"></div><div class="map-road road-three"></div><div class="map-park park-one"></div><div class="map-park park-two"></div><span class="map-street-label street-one">Prabhat Road</span><span class="map-street-label street-two">Model Colony</span><span class="map-route-line" style="${routeLineStyle(riderLocation, deliveryLocation)}"></span><span class="map-pin restaurant-pin" style="left:${restaurantPosition.left}%;top:${restaurantPosition.top}%"><span>⌂</span></span><span class="map-pin home-pin" style="left:${homePosition.left}%;top:${homePosition.top}%"><span>⌖</span></span><span class="rider-pulse" style="left:${riderPosition.left}%;top:${riderPosition.top}%"></span><span class="map-pin" style="left:${riderPosition.left}%;top:${riderPosition.top}%"><span>🛵</span></span><span class="tracking-note">${live ? "Rider location updates automatically" : "Waiting for rider to start sharing"}</span></div><div class="tracking-detail"><div class="progress-track">${steps.map((label, index) => `<div class="progress-step ${index <= status.index ? "done" : ""}">${label}</div>`).join("")}</div><div class="rider-panel"><div class="rider-avatar">R</div><div><strong>${escapeHtml(order.riderName || "Your Foodie rider")}</strong><small>${live ? "Sharing a live location" : "Your rider will appear here soon"}</small></div><div class="rider-actions"><button data-action="call-rider" type="button" aria-label="Call rider">⌕</button><button data-action="chat-rider" type="button" aria-label="Chat with rider">↗</button></div></div><div class="track-actions">${live ? "" : `<button class="primary-button" data-action="start-demo" type="button">Preview live ride <span>→</span></button>`}<button class="secondary-button" data-action="open-rider" type="button">Rider mode</button></div></div></article>`;
  }
  function renderProfile() { const target = document.getElementById("profileContent"); if (!target) return; const configured = state.firebaseConfigured; const orderLine = state.activeOrder ? `Active order ${state.activeOrder.id}` : "No active order right now"; target.innerHTML = `<div class="profile-section-title">Your Foodie</div><div class="profile-list"><button class="profile-row" data-action="open-rider" type="button"><span class="profile-row-icon">🛵</span><span class="profile-row-copy"><strong>Rider mode</strong><small>Share live location for an order</small></span><span class="profile-row-arrow">›</span></button><button class="profile-row" data-action="track-order" type="button"><span class="profile-row-icon">⌁</span><span class="profile-row-copy"><strong>Live order tracking</strong><small>${escapeHtml(orderLine)}</small></span><span class="profile-row-arrow">›</span></button><button class="profile-row" data-action="address" type="button"><span class="profile-row-icon">⌖</span><span class="profile-row-copy"><strong>Saved addresses</strong><small>Home · Pune, Maharashtra</small></span><span class="profile-row-arrow">›</span></button></div><div class="profile-section-title">App settings</div><div class="profile-list"><button class="profile-row" data-action="firebase-help" type="button"><span class="profile-row-icon">◉</span><span class="profile-row-copy"><strong>Realtime connection</strong><small>Firebase Realtime Database</small></span><span class="connection-status ${configured ? "" : "demo"}">${configured ? "Connected" : "Demo mode"}</span></button><button class="profile-row" data-action="notifications" type="button"><span class="profile-row-icon">♢</span><span class="profile-row-copy"><strong>Notifications</strong><small>Order updates and offers</small></span><span class="profile-row-arrow">›</span></button><button class="profile-row" data-action="support" type="button"><span class="profile-row-icon">?</span><span class="profile-row-copy"><strong>Help & support</strong><small>We are here for every craving</small></span><span class="profile-row-arrow">›</span></button></div>`; }
  function renderCartPeek() { const peek = document.getElementById("cartPeek"); if (!peek) return; const count = cartCount(); peek.classList.toggle("hidden", count === 0 || state.modal === "cart" || state.modal === "checkout"); const node = document.getElementById("cartPeekCount"); if (node) node.textContent = `${count} ${count === 1 ? "item" : "items"} · ${money(cartSubtotal())}`; }
  function modalShell(content, label) { modalRoot.innerHTML = `<div class="modal-backdrop" data-action="close-modal" role="dialog" aria-modal="true" aria-label="${escapeHtml(label)}"><div class="modal-sheet" data-modal-sheet><div class="modal-handle"></div>${content}</div></div>`; }
  function renderRestaurantModal() { const restaurant = restaurantById(state.selectedRestaurantId); const items = (menus[restaurant.id] || []).map((item) => { const key = `${restaurant.id}::${item.id}`; const quantity = Number(state.cart[key]) || 0; return `<div class="menu-item"><div class="menu-item-visual">${item.emoji}</div><div class="menu-item-info"><h3><span class="veg-dot ${item.veg ? "" : "nonveg-dot"}"></span>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.description)}</p><div class="menu-item-bottom"><span class="menu-item-price">${money(item.price)}</span><button class="add-button ${quantity ? "added" : ""}" data-action="add-item" data-restaurant-id="${restaurant.id}" data-item-id="${item.id}" type="button">${quantity ? `${quantity} added` : "Add"} <span>${quantity ? "✓" : "+"}</span></button></div></div></div>`; }).join(""); modalShell(`<div class="modal-header"><div><span class="section-kicker">${escapeHtml(restaurant.tag)}</span><h2>${escapeHtml(restaurant.name)}</h2><p>${escapeHtml(restaurant.cuisine)} · ${restaurant.eta}</p></div><button class="modal-close" data-action="close-modal" type="button">×</button></div><div class="menu-list">${items}</div><div class="modal-footer"><button class="primary-button" data-action="open-cart" type="button">${cartCount() ? `View cart · ${money(cartSubtotal())}` : "Build your order"} <span>→</span></button></div>`, `${restaurant.name} menu`); }
  function renderCartModal() { const entries = cartEntries(); if (!entries.length) { modalShell(`<div class="modal-header"><div><span class="section-kicker">Your basket</span><h2>Nothing here yet</h2><p>Choose a restaurant and add a craving.</p></div><button class="modal-close" data-action="close-modal" type="button">×</button></div><div class="empty-state" style="margin:0 22px 22px;min-height:240px"><div><div class="empty-state-emoji">🛍️</div><h3>Let us fix that.</h3><p>Your cart is waiting for something delicious.</p><button class="primary-button" data-action="browse-menu" type="button">Browse menu <span>→</span></button></div></div>`, "Cart"); return; } const rows = entries.map((entry) => `<div class="cart-row"><span class="cart-row-emoji">${entry.emoji}</span><span class="cart-row-copy"><strong>${escapeHtml(entry.name)}</strong><small>${escapeHtml(restaurantById(entry.restaurantId).name)} · ${money(entry.price * entry.quantity)}</small></span><span class="qty-control"><button data-action="cart-change" data-key="${entry.key}" data-delta="-1" type="button">−</button><span>${entry.quantity}</span><button data-action="cart-change" data-key="${entry.key}" data-delta="1" type="button">+</button></span></div>`).join(""); const delivery = cartSubtotal() >= 399 ? 0 : 39; modalShell(`<div class="modal-header"><div><span class="section-kicker">Your basket</span><h2>Ready to checkout?</h2><p>${cartCount()} ${cartCount() === 1 ? "item" : "items"} picked for you.</p></div><button class="modal-close" data-action="close-modal" type="button">×</button></div><div class="cart-list">${rows}</div><div class="modal-footer"><div class="bill-summary"><div class="bill-line"><span>Subtotal</span><strong>${money(cartSubtotal())}</strong></div><div class="bill-line"><span>Delivery fee</span><strong>${delivery ? money(delivery) : "FREE"}</strong></div><div class="bill-line total"><span>Total</span><strong>${money(cartSubtotal() + delivery)}</strong></div></div><button class="primary-button" data-action="checkout" type="button" style="width:100%;margin-top:15px">Continue to checkout <span>→</span></button></div>`, "Your cart"); }
  function renderCheckoutModal() { const delivery = cartSubtotal() >= 399 ? 0 : 39; modalShell(`<div class="modal-header"><div><span class="section-kicker">Almost there</span><h2>Checkout</h2><p>Delivered with care from Foodie.</p></div><button class="modal-close" data-action="close-modal" type="button">×</button></div><div class="form-grid"><label class="form-label">Your name<input id="checkoutName" type="text" value="Sunny" placeholder="e.g. Sunny" /></label><label class="form-label">Phone number<input id="checkoutPhone" type="tel" placeholder="10-digit mobile number" inputmode="numeric" /></label><label class="form-label">Delivery address<textarea id="checkoutAddress" placeholder="Flat, building, street, area">Home, Pune, Maharashtra</textarea></label><div class="form-label">Payment method<div class="payment-options"><label class="payment-option"><input type="radio" name="payment" value="Cash on delivery" checked /> Cash on delivery</label><label class="payment-option"><input type="radio" name="payment" value="UPI on delivery" /> UPI on delivery</label></div></div></div><div class="modal-footer"><div class="bill-summary"><div class="bill-line"><span>To pay</span><strong>${money(cartSubtotal() + delivery)}</strong></div><div class="bill-line"><span>Delivery estimate</span><strong>25–35 min</strong></div></div><button class="primary-button" data-action="place-order" type="button" style="width:100%;margin-top:15px">Place order <span>→</span></button></div>`, "Checkout"); }
  function renderRiderModal() { modalShell(`<div class="modal-header"><div><span class="section-kicker">For delivery partners</span><h2>Rider mode</h2><p>Share your live location with the customer.</p></div><button class="modal-close" data-action="close-modal" type="button">×</button></div><div class="rider-modal-note"><strong>How it works:</strong> enter the order code, allow location access, and keep this page open while delivering. Updates are written to the Firebase Realtime Database.</div>${state.riderSharing ? `<div class="rider-console-state"><strong>● Sharing live location for ${escapeHtml(state.riderOrderId)}</strong><small>${escapeHtml(state.riderName)} · The customer's tracking screen will update automatically.</small></div>` : `<div class="form-grid"><label class="form-label">Order code<input id="riderOrderId" type="text" value="${escapeHtml(state.activeOrder?.id || "")}" placeholder="e.g. FD8K4P2" /></label><label class="form-label">Rider name<input id="riderName" type="text" value="${escapeHtml(state.riderName)}" placeholder="Your name" /></label></div>`}<div class="modal-footer">${state.riderSharing ? `<button class="primary-button" data-action="stop-rider" type="button" style="width:100%;background:#fff0e8;color:#c84e32;box-shadow:none">Stop sharing <span>×</span></button>` : `<button class="primary-button" data-action="start-rider" type="button" style="width:100%">Start sharing location <span>→</span></button>`}</div>`, "Rider mode"); }
  function renderInfoModal(title, heading, message, emoji) { modalShell(`<div class="modal-header"><div><span class="section-kicker">Foodie</span><h2>${escapeHtml(title)}</h2><p>Made for a smoother delivery day.</p></div><button class="modal-close" data-action="close-modal" type="button">×</button></div><div class="empty-state" style="margin:0 22px 22px;min-height:230px"><div><div class="empty-state-emoji">${emoji}</div><h3>${escapeHtml(heading)}</h3><p>${escapeHtml(message)}</p><button class="primary-button" data-action="close-modal" type="button">Done <span>✓</span></button></div></div>`, title); }
  function renderModal() { if (!state.modal) { modalRoot.innerHTML = ""; renderCartPeek(); return; } if (state.modal === "restaurant") renderRestaurantModal(); if (state.modal === "cart") renderCartModal(); if (state.modal === "checkout") renderCheckoutModal(); if (state.modal === "rider") renderRiderModal(); if (state.modal === "notifications") renderInfoModal("Notifications", "You are all caught up", "When your order moves, Foodie will keep you posted right here.", "🔔"); if (state.modal === "location") renderInfoModal("Your delivery spot", "Pune, Maharashtra", "Foodie is showing restaurants around your saved home location.", "⌖"); if (state.modal === "support") renderInfoModal("Need a hand?", "We have got you", "For this demo, use the rider console to test live location sharing, or connect Firebase to save real orders.", "💬"); if (state.modal === "firebase") renderFirebaseModal(); if (state.modal === "filters") renderFilterModal(); renderCartPeek(); }
  function renderFirebaseModal() { modalShell(`<div class="modal-header"><div><span class="section-kicker">Connection</span><h2>${state.firebaseConfigured ? "Firebase is connected" : "Demo mode is on"}</h2><p>Realtime Database status</p></div><button class="modal-close" data-action="close-modal" type="button">×</button></div><div class="rider-modal-note">${state.firebaseConfigured ? "Orders and rider location updates can now sync between devices." : "Add your Firebase web config in firebase-config.js to sync orders and rider locations between devices. The rest of the app is ready to explore locally."}</div><div class="modal-footer"><button class="primary-button" data-action="close-modal" type="button" style="width:100%">Got it <span>✓</span></button></div>`, "Firebase status"); }
  function renderFilterModal() { modalShell(`<div class="modal-header"><div><span class="section-kicker">Discover</span><h2>Filter cravings</h2><p>Choose a category to tune your feed.</p></div><button class="modal-close" data-action="close-modal" type="button">×</button></div><div class="category-rail" style="padding:0 22px 20px;flex-wrap:wrap">${categories.map((category) => `<button class="category-chip ${state.activeCategory === category.id ? "active" : ""}" data-action="category" data-category="${category.id}" type="button"><span class="category-icon">${category.icon}</span><span>${category.label}</span></button>`).join("")}</div><div class="modal-footer"><button class="primary-button" data-action="close-modal" type="button" style="width:100%">Show ${state.activeCategory === "All" ? "everything" : state.activeCategory} <span>→</span></button></div>`, "Filters"); }
  function closeModal() { state.modal = null; modalRoot.innerHTML = ""; renderCartPeek(); }
  function createOrderFromCart() { const entries = cartEntries(); const restaurantId = entries[0]?.restaurantId || restaurants[0].id; const delivery = cartSubtotal() >= 399 ? 0 : 39; return { id: `FD${Date.now().toString(36).slice(-7).toUpperCase()}`, restaurantId, items: entries.map((entry) => ({ id: entry.id, name: entry.name, quantity: entry.quantity, price: entry.price })), subtotal: cartSubtotal(), delivery, total: cartSubtotal() + delivery, status: "confirmed", customer: { name: "Sunny", phone: "", address: "Home, Pune, Maharashtra", payment: "Cash on delivery" }, createdAt: Date.now(), riderName: "Foodie Rider" }; }
  async function placeOrder() { if (!cartEntries().length) { showToast("Add something to your cart first"); return; } const name = document.getElementById("checkoutName")?.value.trim() || "Sunny"; const phone = document.getElementById("checkoutPhone")?.value.trim() || ""; const address = document.getElementById("checkoutAddress")?.value.trim() || "Home, Pune, Maharashtra"; const payment = document.querySelector('input[name="payment"]:checked')?.value || "Cash on delivery"; if (phone && !/^\+?[0-9 ()-]{8,15}$/.test(phone)) { showToast("Please enter a valid phone number"); return; } const order = createOrderFromCart(); order.customer = { name, phone, address, payment }; state.activeOrder = order; state.orders = [order, ...state.orders.filter((existing) => existing.id !== order.id)]; state.cart = {}; persist(); const db = firebaseApi(); if (db?.configured) { try { await db.set(`orders/${order.id}`, { ...order, createdAt: db.serverTimestamp() }); showToast("Order placed — your kitchen is on it!"); } catch (error) { console.warn("Order write failed", error); showToast("Order saved on this device; Firebase needs a rules check"); } } else showToast("Order placed in demo mode"); closeModal(); setView("track"); }
  function subscribeToRider(orderId) { if (!orderId || state.listeningOrderId === orderId) return; if (typeof state.locationUnsubscribe === "function") state.locationUnsubscribe(); state.locationUnsubscribe = null; state.listeningOrderId = orderId; state.liveLocation = null; state.liveIsFirebase = false; const db = firebaseApi(); if (!db?.configured) { renderTrack(); return; } state.locationUnsubscribe = db.listen(`riderLocations/${orderId}`, (location) => { if (!location || typeof location.lat !== "number" || typeof location.lng !== "number") return; state.liveLocation = location; state.liveIsFirebase = true; state.activeOrder = { ...state.activeOrder, riderName: location.riderName || state.activeOrder.riderName, status: location.status || state.activeOrder.status }; persist(); renderTrack(); }, (error) => console.warn("Rider location listener failed", error)); }
  function demoLocation(step) { const from = restaurantById(state.activeOrder?.restaurantId).location; const t = (Math.sin(step / 2) + 1) / 2 * .16 + Math.min(step / 14, .68); return { lat: from.lat + (deliveryLocation.lat - from.lat) * t, lng: from.lng + (deliveryLocation.lng - from.lng) * t }; }
  function startDemoRider() { if (!state.activeOrder) { const restaurant = restaurantById("saffron-yard"); const item = menus[restaurant.id][0]; state.activeOrder = { id: "FDDEMO01", restaurantId: restaurant.id, items: [{ id: item.id, name: item.name, quantity: 1, price: item.price }], subtotal: item.price, delivery: 0, total: item.price, status: "on_the_way", customer: { name: "Sunny", address: "Home, Pune, Maharashtra" }, createdAt: Date.now(), riderName: "Aarav · Foodie Rider" }; state.orders = [state.activeOrder, ...state.orders]; persist(); } state.activeOrder = { ...state.activeOrder, status: "on_the_way", riderName: state.activeOrder.riderName || "Aarav · Foodie Rider" }; state.demoStep = 0; clearInterval(state.demoTimer); state.liveIsFirebase = false; state.liveLocation = demoLocation(0); state.demoTimer = setInterval(() => { state.demoStep += 1; if (state.demoStep > 14) { clearInterval(state.demoTimer); state.demoTimer = null; state.activeOrder = { ...state.activeOrder, status: "delivered" }; } state.liveLocation = demoLocation(Math.min(state.demoStep, 14)); persist(); renderTrack(); }, 2200); persist(); setView("track"); showToast("Demo rider is moving live on the map"); }
  async function startRiderSharing() { const orderId = (document.getElementById("riderOrderId")?.value.trim() || state.activeOrder?.id || "").toUpperCase(); const riderName = document.getElementById("riderName")?.value.trim() || "Foodie Rider"; if (!orderId) { showToast("Enter the customer's order code first"); return; } state.riderOrderId = orderId; state.riderName = riderName; state.riderSharing = true; clearInterval(state.demoTimer); state.demoTimer = null; renderModal(); const db = firebaseApi(); if (db?.configured) { try { const presence = db.ref(`riderPresence/${orderId}`); await db.set(presence, { online: true, riderName, updatedAt: db.serverTimestamp() }); await db.onDisconnect(presence).set({ online: false, riderName, updatedAt: db.serverTimestamp() }); } catch (error) { console.warn("Presence write failed", error); } } const publish = async (position) => { const payload = { lat: Number(position.coords.latitude), lng: Number(position.coords.longitude), heading: position.coords.heading == null ? null : Number(position.coords.heading), speed: position.coords.speed == null ? null : Number(position.coords.speed), riderName, status: "on_the_way", updatedAt: db?.configured ? db.serverTimestamp() : Date.now() }; state.liveLocation = { ...payload, updatedAt: Date.now() }; state.liveIsFirebase = Boolean(db?.configured); if (db?.configured) { try { await db.set(`riderLocations/${orderId}`, payload); await db.update(`orders/${orderId}`, { status: "on_the_way", riderName }); } catch (error) { console.warn("Location write failed", error); showToast("Location read worked, but Firebase rejected the write"); } } if (state.activeOrder?.id === orderId) { state.activeOrder = { ...state.activeOrder, status: "on_the_way", riderName }; persist(); } renderTrack(); }; if (!navigator.geolocation) { showToast("Location is not available here — showing a local demo"); startDemoRider(); return; } state.riderWatchId = navigator.geolocation.watchPosition(publish, () => { showToast("Location permission was unavailable — showing a local demo"); startDemoRider(); }, { enableHighAccuracy: true, maximumAge: 5000, timeout: 12000 }); showToast(db?.configured ? "Live location sharing started" : "Sharing a local rider preview"); }
  async function stopRiderSharing() { if (state.riderWatchId !== null) navigator.geolocation?.clearWatch(state.riderWatchId); state.riderWatchId = null; state.riderSharing = false; const db = firebaseApi(); if (db?.configured && state.riderOrderId) { try { await db.update(`riderPresence/${state.riderOrderId}`, { online: false, riderName: state.riderName, updatedAt: db.serverTimestamp() }); } catch (error) { console.warn("Presence close failed", error); } } renderModal(); showToast("Live location sharing stopped"); }
  function reorder(orderId) { const order = state.orders.find((entry) => entry.id === orderId); if (!order) return; order.items.forEach((item) => { state.cart[`${order.restaurantId}::${item.id}`] = item.quantity; }); persist(); setView("home"); showToast("Your favourites are back in the cart"); setTimeout(() => { state.modal = "cart"; renderModal(); }, 260); }
  function changeCart(key, delta) { const next = (Number(state.cart[key]) || 0) + delta; if (next <= 0) delete state.cart[key]; else state.cart[key] = next; persist(); renderView(state.view); if (state.modal) renderModal(); }
  function addToCart(restaurantId, itemId) { const key = `${restaurantId}::${itemId}`; state.cart[key] = (Number(state.cart[key]) || 0) + 1; persist(); renderView(state.view); renderModal(); showToast("Added to your cart"); }
  function handleAction(action, element) {
    if (action === "close-modal") { closeModal(); return; }
    if (action === "category") { state.activeCategory = element.dataset.category || "All"; state.modal = state.modal === "filters" ? null : state.modal; renderView("home"); if (state.modal) renderModal(); return; }
    if (action === "open-restaurant") { state.selectedRestaurantId = element.dataset.restaurantId; state.modal = "restaurant"; renderModal(); return; }
    if (action === "favorite") { element.textContent = element.textContent.trim() === "♥" ? "♡" : "♥"; element.style.color = element.textContent === "♥" ? "#ffddd0" : "#fff"; showToast(element.textContent === "♥" ? "Saved to your favourites" : "Removed from favourites"); return; }
    if (action === "add-item") { addToCart(element.dataset.restaurantId, element.dataset.itemId); return; }
    if (action === "cart-change") { changeCart(element.dataset.key, Number(element.dataset.delta)); return; }
    if (action === "open-cart") { state.modal = "cart"; renderModal(); return; }
    if (action === "checkout") { state.modal = "checkout"; renderModal(); return; }
    if (action === "place-order") { placeOrder(); return; }
    if (action === "track-order") { state.activeOrder ? setView("track") : showToast("You do not have an active order yet"); return; }
    if (action === "start-demo") { startDemoRider(); return; }
    if (action === "open-rider") { state.modal = "rider"; renderModal(); return; }
    if (action === "start-rider") { startRiderSharing(); return; }
    if (action === "stop-rider") { stopRiderSharing(); return; }
    if (action === "reorder") { reorder(element.dataset.orderId); return; }
    if (action === "notifications") { state.modal = "notifications"; renderModal(); return; }
    if (action === "location") { state.modal = "location"; renderModal(); return; }
    if (action === "firebase-help") { state.modal = "firebase"; renderModal(); return; }
    if (action === "support") { state.modal = "support"; renderModal(); return; }
    if (action === "address" || action === "edit-profile") { showToast("Profile editing is ready for your next customisation"); return; }
    if (action === "call-rider") { window.location.href = "tel:+919999999999"; return; }
    if (action === "chat-rider") { showToast("Rider chat will open when messaging is connected"); return; }
    if (action === "copy-code") { navigator.clipboard?.writeText("HUNGRY50").catch(() => {}); showToast("Code HUNGRY50 copied"); return; }
    if (action === "filters") { state.modal = "filters"; renderModal(); return; }
    if (action === "show-all-categories") { state.activeCategory = "All"; renderView("home"); document.getElementById("categoryRail")?.scrollIntoView({ behavior: "smooth", block: "center" }); return; }
    if (action === "browse-menu") { setView("home"); setTimeout(() => document.getElementById("restaurantGrid")?.scrollIntoView({ behavior: "smooth", block: "center" }), 80); return; }
    if (action === "back-home") setView("home");
  }
  document.addEventListener("click", (event) => { const nav = event.target.closest("[data-view]"); if (nav) { setView(nav.dataset.view); return; } const action = event.target.closest("[data-action]"); if (action) handleAction(action.dataset.action, action); });
  document.addEventListener("keydown", (event) => { if (event.key === "Escape" && state.modal) closeModal(); if (event.key === "Enter" && event.target.closest(".restaurant-card")) { state.selectedRestaurantId = event.target.closest(".restaurant-card").dataset.restaurantId; state.modal = "restaurant"; renderModal(); } });
  document.addEventListener("input", (event) => { if (event.target.id === "searchInput") { state.search = event.target.value; renderRestaurants(); } });
  window.addEventListener("foodie-firebase-ready", (event) => { state.firebaseConfigured = Boolean(event.detail?.configured); renderProfile(); if (state.activeOrder && state.view === "track") subscribeToRider(state.activeOrder.id); });
  renderView("home"); if (state.activeOrder) subscribeToRider(state.activeOrder.id);
})();
